version: "3"
services:

  app:
    container_name: react-skole-blog
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    volumes:
      - ./ :/app
      - /app/node_modules
    command: "npm start"
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    